# Generated by Django 5.2.5 on 2025-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ahmagh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
    ]
