# Generated by Django 5.2.5 on 2025-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_app', '0002_ahmagh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ahmagh',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='icon',
            new_name='icon_name',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_style',
            field=models.CharField(default='fab', max_length=10),
            preserve_default=False,
        ),
    ]
