# Generated by Django 5.2.5 on 2025-08-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_app', '0003_delete_ahmagh_rename_icon_sociallink_icon_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_text',
            field=models.CharField(default='© 2025', max_length=200),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='onepage_app.profile')),
            ],
        ),
    ]
