# Generated by Django 5.2.5 on 2025-08-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage_app', '0004_cv_alter_profile_footer_text_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='onepage_app.profile'),
            preserve_default=False,
        ),
    ]
