# Generated by Django 5.2.3 on 2025-06-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='salart',
            new_name='salary',
        ),
    ]
